spring:
  application:
    name: finvibe-backend-batch
  main:
    allow-bean-definition-overriding: true
    web-application-type: none
  config:
    import:
      - optional:file:.env[.properties]
      - optional:file:../Finvibe_Backend_Monolith/src/main/resources/application.yml
      - optional:file:../Finvibe_Backend_Monolith/src/main/resources/application-local.yml
  batch:
    job:
      enabled: false
